/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MintingTokenASol from "./ERC20_MintingTokenA.sol";
export type { erc20MintingTokenASol };
import type * as erc20MintingTokenBSol from "./ERC20_MintingTokenB.sol";
export type { erc20MintingTokenBSol };
import type * as erc20TokenSwappingContractSol from "./ERC20_TokenSwappingContract.sol";
export type { erc20TokenSwappingContractSol };
