/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20MintingTokenASol from "./ERC20_MintingTokenA.sol";
export * as erc20MintingTokenBSol from "./ERC20_MintingTokenB.sol";
export * as erc20TokenSwappingContractSol from "./ERC20_TokenSwappingContract.sol";
